services:
  - type: web
    name: mlb-betting-system
    env: python
    region: oregon
    plan: free
    runtime: python
    pythonVersion: "3.11.9"
    buildCommand: bash build.sh
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 180 --max-requests 1000 --preload
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_ENV
        value: production
      - key: WEATHER_API_KEY
        value: 487d8b3060df1751a73e0f242629f0ca
      - key: PYTHONPATH
        value: "."
      - key: PYTHONUNBUFFERED
        value: "1"
