services:
  - type: web
    name: mlb-betting-system
    env: python
    region: oregon
    plan: free
    runtime: python
    pythonVersion: "3.11.9"
    buildCommand: bash build.sh
  startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 120 --max-requests 1000 --preload
  healthCheckPath: /api/diag
    # Note: No persistent disk on web to avoid shadowing repo 'data' folder with empty volume.
    # The app reads git-tracked daily files immediately after deploy. A separate worker can
    # maintain a disk if needed for persistence.
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: FLASK_ENV
        value: production
      - key: WEATHER_API_KEY
        value: REPLACE_IN_RENDER_UI
      - key: PYTHONPATH
        value: "."
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: ENABLE_PERIODIC_WARM
        value: "1"
      - key: PERIODIC_WARM_INTERVAL_SECONDS
        value: "480"
      # IMPORTANT: Set the same token value here and on the worker service
      - key: PITCHER_SSE_INGEST_TOKEN
        value: REPLACE_IN_RENDER_UI
  - type: worker
    name: mlb-betting-props-updater
    env: python
    region: oregon
    plan: free
    runtime: python
    pythonVersion: "3.11.9"
    buildCommand: bash build.sh
    startCommand: python continuous_pitcher_props_updater.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: PYTHONPATH
        value: "."
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PITCHER_PROPS_POLL_INTERVAL_SEC
        value: "600"
      - key: PITCHER_PROPS_FAST_INTERVAL_SEC
        value: "180"
      - key: PITCHER_PROPS_MAX_AGE_MIN
        value: "480"
      - key: PITCHER_PROPS_MIN_MARKETS
        value: "1"
      - key: PITCHER_PROPS_SSE_MAX_EVENTS
        value: "20"
      # Enable git syncing of data dir (commits on changes and at exit)
      - key: PITCHER_PROPS_AUTO_GIT
        value: "1"
      # Secure token to allow worker to push events/files to web app if using cross-process ingest
      - key: PITCHER_SSE_INGEST_TOKEN
        value: REPLACE_IN_RENDER_UI
      # Required for bridge: set to your web service URL (e.g., https://mlb-betting-system.onrender.com)
      - key: WEB_BASE_URL
        value: "https://mlb-betting-system.onrender.com"
      # Optional PAT-based git writeback bootstrap (see build.sh). Set these ONLY in Render UI.
      # - key: GIT_WRITE_ENABLE
      #   value: "1"
      # - key: GIT_PAT
      #   value: "<set as Secret in Render UI>"
      # - key: GIT_REPO_HTTPS
      #   value: "https://github.com/mostgood1/MLBBetting.git"
      # - key: GIT_USER_EMAIL
      #   value: "bot@mlb-betting.local"
      # - key: GIT_USER_NAME
      #   value: "mlb-betting-bot"
